[package]
name = "simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base" }
fa = { path = "../fa" }

log = "0.4"
yew = { git = "https://github.com/yewstack/yew.git", rev = "421b4e1f608e6d648dcf571157b081fcbd886996" }
strum = { version = "0.24", features = ["derive"] }
ywt = { git = "https://github.com/tdooms/ywt.git"}