[package]
name = "cobul"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["base", "fa", "test", "scraper", "simple", "extensions", "derive"]

[dependencies]
base = { path = "base" }
extensions = { path = "extensions", optional = true }
simple = { path = "simple", optional = true }
fa = { path = "fa", optional = true }



