[package]
name = "cobul"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["base", "custom", "fa", "test", "fa_scraper", "forms", "util"]

[dependencies]
base = { path = "base" }
custom = { path = "custom", optional = true }
util = { path = "util", optional = true }
fa = { path = "fa", optional = true }
forms = { path = "forms", optional = true }



