[package]
name = "cobul"
license = "MIT"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["base", "fa", "test", "scraper", "simple", "extensions"]

[dependencies]
base = { path = "base", version = "0.1.0" }
extensions = { path = "extensions", optional = true, version = "0.1.0" }
simple = { path = "simple", optional = true, version = "0.1.0" }
fa = { path = "fa", optional = true, version = "0.1.0" }



