[package]
name = "cobul"
version = "0.1.0"
edition = "2018"

[workspace]
members = ["base", "custom", "fa", "test", "fa_scraper"]

[dependencies]
base = { path = "base" }
custom = { path = "custom", optional = true }
fa = { path = "fa", optional = true }



