[package]
name = "cobul"
license = "MIT"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["base", "fa", "test", "scraper", "simple", "extensions"]

[features]
default = ["base"]
base = ["cobul_base"]
extensions = ["cobul_extensions"]
simple = ["cobul_simple"]
fa = ["cobul_fa"]

[dependencies]
cobul_base = { path = "base", optional = true }
cobul_extensions = { path = "extensions", optional = true }
cobul_simple = { path = "simple", optional = true}
cobul_fa = { path = "fa", optional = true }



