[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0" }
syn = { version = "1.0" }
proc-macro2 = { version = "1.0" }
darling = { version = "0.14" }