[package]
name = "custom"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base" }

yew = "0.19.3"
web-sys = "0.3"

strum = { version = "0.21", features = ["derive"] }
derive_more = "0.99.16"
num = "0.4"